create table if not exists teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  group_name text,
  logo_url text,
  ranking_points integer not null default 100,
  created_at timestamptz default now()
);

create table if not exists matches (
  id bigint generated by default as identity primary key,
  home_team_id bigint references teams(id) on delete cascade,
  away_team_id bigint references teams(id) on delete cascade,
  home_score integer not null default 0,
  away_score integer not null default 0,
  match_date timestamptz,
  status text not null default 'scheduled',
  created_at timestamptz default now()
);

create table if not exists team_honors (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  title text not null,
  season text,
  created_at timestamptz default now()
);

create table if not exists players (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  name text not null,
  number integer,
  position text,
  goals integer not null default 0,
  assists integer not null default 0
);

create table if not exists ranking_history (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  points integer not null,
  reason text,
  match_id bigint references matches(id) on delete set null,
  created_at timestamptz default now()
);

insert into teams (name, group_name)
values
('قبربابا','A'),
('دره بادام','A'),
('دوردشت','A'),
('علیباقر','B'),
('تلل','B'),
('زمان','B'),
('گلستان','C'),
('ده موسی','C'),
('الکه','C'),
('سرجوب','D'),
('پرگلی','D'),
('ده عباسیان','D')
on conflict (name) do nothing;